# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

menu:
  "u":
    desc: Utilities
    submenu:
      "BackSpace": { desc: System Actions, cmd: "sysact" }
      "F3": { desc: Display Select, cmd: "displayselect" }
      "F4": { desc: Audio Mixer, cmd: "$TERMINAL -e pulsemixer" }
      "F7": { desc: Unicode Picker, cmd: "dmenuunicode" }
      "F8": { desc: Screenshot, cmd: "maimpick-wl" }
      "m": { desc: Mounter, cmd: "mounter" }
      "u": { desc: Unmounter, cmd: "unmounter" }
      "d": { desc: Display Configuration, cmd: "wdisplays" }
      "s": { desc: System Monitor, cmd: "$TERMINAL -e btop" }

  "m":
    desc: Media
    submenu:
      "minus": { desc: Volume -5%, cmd: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-" }
      "plus": { desc: Volume +5%, cmd: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+" }
      "m": { desc: Toggle Mute, cmd: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle" }
      "n": { desc: Next Track, cmd: "mpc next" }
      "p": { desc: Previous Track, cmd: "mpc prev" }
      "Return": { desc: Play, cmd: "mpc play" }
      "space": { desc: Pause, cmd: "mpc pause" }
      "s": { desc: Stop, cmd: "mpc stop" }

  "b":
    desc: Control Center
    submenu:
      "u": { desc: Increase Brightness, cmd: "brightnessctl set +15%" }
      "d": { desc: Decrease Brightness, cmd: "brightnessctl set 15%-" }

  "a":
    desc: Apps
    submenu:
      "p": { desc: Music Player, cmd: "$MUSICPLAYER" }
      "e": { desc: Email Client, cmd: "$EMAILCLIENT" }
      "y": { desc: Terminal YouTube Browser, cmd: "$TERMINAL -e ytfzf -t" }
      "n": { desc: Notes (VimWiki), cmd: "$TERMINAL -e nvim -c WikiIndex" }
      "r": { desc: Terminal File Manager, cmd: "$TERMINAL -e lfub" }

  "l":
    desc: Layouts
    submenu:
      "t": { desc: Tiled Layout, cmd: "dwlmsg -s -l 0" }
      "f": { desc: Floating Layout, cmd: "dwlmsg -s -l 1" }
      "m": { desc: Monocle Layout, cmd: "dwlmsg -s -l 2" }

  "x":
    desc: Session
    submenu:
      "q": { desc: Quit dwl, cmd: "dwlmsg -s -c quit" }
      "s": { desc: Suspend (systemd), cmd: "systemctl suspend" }
      "h": { desc: Hibernate (systemd), cmd: "systemctl hibernate" }
      "r": { desc: Reboot (systemd), cmd: "systemctl reboot" }
      "p": { desc: Poweroff (systemd), cmd: "systemctl poweroff" }
