#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.


setbg ~/.local/share/wallpapers &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
xsettingsd &		# Start the settings daemon.
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xset r rate 300 50 &	# Speed xrate up
xset s noblank
st -e tmux &
xcompmgr &
dunst &
unclutter &
clipmenud &

xidlehook --not-when-fullscreen --not-when-audio \
--timer 60 \
'for display in $(xrandr --listactivemonitors | grep -oP "(DisplayPort|HDMI)-[A-Z]*[0-9]$"); do xrandr --output "$display" --brightness .1; done' \
'for display in $(xrandr --listactivemonitors | grep -oP "(DisplayPort|HDMI)-[A-Z]*[0-9]$"); do xrandr --output "$display" --brightness 1; done' \
--timer 10 'for display in $(xrandr --listactivemonitors | grep -oP "(DisplayPort|HDMI)-[A-Z]*[0-9]$"); do xrandr --output "$display" --brightness 1; done; slock' '' \
--timer 3600 'systemctl hibernate' '' &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

#xidlehook \
#--not-when-fullscreen \
#--not-when-audio \
#--timer 60 \
#'xrandr --output "$PRIMARY_DISPLAY" --brightness .1' \
#'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
#--timer 10 \
#'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; slock' \
#'' \
#--timer 3600 \
#'systemctl suspend' \
#''
